# Generated by Django 4.2.4 on 2024-03-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubInfoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=100)),
                ('language_percentages', models.JSONField()),
                ('last_active', models.DateTimeField(null=True)),
                ('cache_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
