FROM python:3.10.12
COPY . /app/backend
WORKDIR /app/backend
RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput
CMD ["gunicorn", "--config", "gunicorn_config.py", "backend.wsgi:application"]
